const files = [
  "scripts/modules/Seguridad.sql",
  "scripts/modules/Auditoria.sql",
  "scripts/modules/Secretaria/Facturacion.sql",
  "scripts/modules/Secretaria/FacturaDiagnostico.sql",
  "scripts/modules/Secretaria/Dashboard.sql",
  "scripts/modules/Secretaria/Garantias.sql",
  "scripts/modules/Secretaria/InventarioStock.sql",
  "scripts/modules/Secretaria/FlujoEstados.sql",
  "scripts/modules/Secretaria/PaginacionIndices.sql",
  "scripts/modules/JefeTecnico/Indices.sql",
  "scripts/modules/JefeTecnico/Supervision.sql",
  "scripts/modules/JefeTecnico/Correcciones.sql",
  "scripts/modules/Tecnico/Trabajo.sql",
  "scripts/modules/admin_pro/00_schema.sql",
  "scripts/modules/admin_pro/01_reportes.sql",
  "scripts/modules/Tecnico/Presupuesto.sql",
  "scripts/modules/LegacyCleanup.sql"
];
