-- Ampliación del historial existente sin alterar trabajos, solicitudes o cantidades.
ALTER TABLE "IntervencionesTecnicas" DROP CONSTRAINT IF EXISTS chk_intervencion_tipo_motivo;
ALTER TABLE "IntervencionesTecnicas" ADD CONSTRAINT chk_intervencion_tipo_motivo CHECK (
  tipo IN ('REASIGNACION','FINALIZACION','CORRECCION_REPUESTO','RETIRAR_APROBACION',
    'REABRIR_SOLICITUD','CORREGIR_ENTREGA','DEVOLUCION_REPUESTO',
    'CORRECCION_CIERRE','ACLARACION_CIERRE','CORRECCION_FOTO_CIERRE','REAPERTURA_CIERRE',
    'CORRECCION_DIAGNOSTICO','ACLARACION_DIAGNOSTICO','REAPERTURA_DIAGNOSTICO','CORRECCION_AVANCE',
    'CORRECCION_SOLICITUD_TECNICO','RETIRO_SOLICITUD_TECNICO',
    'CORRECCION_IRREPARABLE','RETIRO_IRREPARABLE','REVISION_FOTO_TECNICA')
  AND NULLIF(BTRIM(motivo),'') IS NOT NULL
  AND (tipo IN ('REASIGNACION','CORRECCION_DIAGNOSTICO','ACLARACION_DIAGNOSTICO','REAPERTURA_DIAGNOSTICO','CORRECCION_AVANCE','REVISION_FOTO_TECNICA') OR orden_id IS NOT NULL)
);
