import React from 'react';
const fecha = (v) => v ? new Date(v).toLocaleString('es-NI', { timeZone: 'America/Managua' }) : 'Pendiente';
export default function RepuestosTable({ solicitudes, loading, onOpenOrden }) {
  return <div className="tecnico-table tecnico-table-repuestos overflow-x-auto rounded-xl border border-slate-200 bg-white text-slate-900"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4" scope="col">Orden</th><th className="p-4" scope="col">Pieza</th><th className="p-4" scope="col">Cantidad</th><th className="p-4" scope="col">Aprobación</th><th className="p-4" scope="col">Entrega física</th></tr></thead><tbody className="divide-y">{solicitudes.map((p) => <tr key={p.id}>
    <td className="p-4"><span className="tecnico-cell-label" aria-hidden="true">Orden</span><button className="text-indigo-700 underline" onClick={() => onOpenOrden?.(p.ordenId)}>#{p.ordenId}</button><p className="mt-1 text-xs">Solicitada: {fecha(p.fecha_solicitud)}</p></td>
    <td className="p-4 font-semibold"><span className="tecnico-cell-label" aria-hidden="true">Pieza</span>{p.repuesto}{p.pendienteInventario && <p className="mt-1 text-xs text-amber-700">Por registrar en inventario</p>}</td><td className="p-4"><span className="tecnico-cell-label" aria-hidden="true">Cantidad</span>{p.cantidad}</td>
    <td className="p-4"><span className="tecnico-cell-label" aria-hidden="true">Aprobación</span><strong className={p.estado === 'DENEGADO' ? 'text-red-700' : p.estado === 'APROBADO' ? 'text-emerald-700' : 'text-amber-700'}>{p.estado === 'DENEGADO' ? 'Rechazada' : p.estado === 'APROBADO' ? 'Aprobada' : 'Pendiente'}</strong><p className="mt-1 text-xs">{fecha(p.fecha_aprobacion)}</p>{p.aprobador && <p className="text-xs">Revisó: {p.aprobador}</p>}{p.motivo && <p className="mt-1 text-xs text-red-700">{p.motivo}</p>}{p.estado === 'PENDIENTE' && <button type="button" onClick={() => onOpenOrden?.(p.ordenId)} className="mt-2 block text-xs font-semibold text-indigo-700 underline">Corregir o retirar</button>}</td>
    <td className="p-4"><span className="tecnico-cell-label" aria-hidden="true">Entrega física</span><strong>{p.estadoEntrega === 'ENTREGADO' ? 'Entregada' : p.estado === 'APROBADO' ? 'Pendiente de entrega' : 'Sin entrega'}</strong>{p.fecha_entrega && <p className="mt-1 text-xs">{fecha(p.fecha_entrega)}</p>}{p.entregador && <p className="text-xs">Entregó: {p.entregador}</p>}</td>
  </tr>)}{!loading && !solicitudes.length && <tr><td colSpan={5} className="p-8 text-center text-slate-500">No hay solicitudes que coincidan con los filtros.</td></tr>}</tbody></table></div>;
}
