import React from 'react';
const fecha = (v) => v ? new Date(v).toLocaleString('es-NI', { timeZone: 'America/Managua' }) : 'Pendiente';
export default function RepuestosTable({ solicitudes, loading, onOpenOrden }) {
  return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white text-slate-900"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">Orden</th><th className="p-4">Pieza</th><th className="p-4">Cantidad</th><th className="p-4">Aprobación</th><th className="p-4">Entrega física</th></tr></thead><tbody className="divide-y">{solicitudes.map((p) => <tr key={p.id}>
    <td className="p-4"><button className="text-indigo-700 underline" onClick={() => onOpenOrden?.(p.ordenId)}>#{p.ordenId}</button><p className="mt-1 text-xs">Solicitada: {fecha(p.fecha_solicitud)}</p></td>
    <td className="p-4 font-semibold">{p.repuesto}{p.pendienteInventario && <p className="mt-1 text-xs text-amber-700">Por registrar en inventario</p>}</td><td className="p-4">{p.cantidad}</td>
    <td className="p-4"><strong className={p.estado === 'DENEGADO' ? 'text-red-700' : p.estado === 'APROBADO' ? 'text-emerald-700' : 'text-amber-700'}>{p.estado === 'DENEGADO' ? 'Rechazada' : p.estado === 'APROBADO' ? 'Aprobada' : 'Pendiente'}</strong><p className="mt-1 text-xs">{fecha(p.fecha_aprobacion)}</p>{p.aprobador && <p className="text-xs">Revisó: {p.aprobador}</p>}{p.motivo && <p className="mt-1 text-xs text-red-700">{p.motivo}</p>}</td>
    <td className="p-4"><strong>{p.estadoEntrega === 'ENTREGADO' ? 'Entregada' : p.estado === 'APROBADO' ? 'Pendiente de entrega' : 'Sin entrega'}</strong>{p.fecha_entrega && <p className="mt-1 text-xs">{fecha(p.fecha_entrega)}</p>}{p.entregador && <p className="text-xs">Entregó: {p.entregador}</p>}</td>
  </tr>)}{!loading && !solicitudes.length && <tr><td colSpan={5} className="p-8 text-center text-slate-500">No hay solicitudes que coincidan con los filtros.</td></tr>}</tbody></table></div>;
}
